name: onPush - e2e tests, deploy staging on FTP

on:
  push:
    branches:
      - dev
      # - 'feature/**'
jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm i

      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          # record: true
          start: npm run start
          wait-on: http://localhost:4200

        # env:
        # pass the Dashboard record key as an environment variable
        # CYPRESS_RECORD_KEY: 86d48a80-01ec-449f-9f7d-5624c3573322

      - name: Build staging
        run: npm run staging

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Deploy FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.vevida.com
          # tmp limited access account for assessment purposes
          username: due-volte.nl2
          password: Fdx36393639assessment
          server-dir: /${{ steps.package-version.outputs.current-version}}-dev/
          log-level: verbose
          local-dir: ./dist/
          # exclude: svg/*
