name: cron - e2e tests, on live server [dev] (every 12hours)

on:
  schedule:
    - cron: "0 */12 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: dev

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm i

      - name: Run Cypress on dev
        uses: cypress-io/github-action@v2
        with:
          # record: true
          start: npm run start:e2e
          config: requestTimeout=100000,responseTimeout=100000,pageLoadTimeout=100000,baseUrl=https://www.due-volte.nl/ssan/fdx/0.1.0-dev
        # env:
        # pass the Dashboard record key as an environment variable
        # CYPRESS_RECORD_KEY: 86d48a80-01ec-449f-9f7d-5624c3573322
